version: '3.8'

services:
  php:
    image: php:8.1-fpm
    container_name: php-container
    volumes:
      - ./src:/var/www/html

  nginx:
    image: nginx
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src:/var/www/html
    depends_on:
      - php
