version: '3.8'

services:
  app:
    tty: true
    image: python
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/fastapi
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: fastapi_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"


  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"

