version: '3.8'

services:
  books-service:
    image: manloralm/books-reviewer
    container_name: books-reviewer
    ports:
      - 8080:8080
    

  nginx:
    image: nginx
    container_name: nginx-container
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    
    
